config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end

 # post 'purchases/:product_id/create', to: 'purchases#create'

  get  'users/:id/purchases', to: 'users#purchases'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products do
    resources :purchases, only: :create
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/maker.rb
class Maker < ApplicationRecord
    has_many :products
end

app/models/price.rb
class Price < ApplicationRecord
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    validates :product_code, presence: true, uniqueness: true
    validates :name, presence: true
    validates :maker_id, presence: true


    belongs_to :maker
    belongs_to :category
    has_one :price
    has_one :stock
    has_many :purchases
    accepts_nested_attributes_for :price
    accepts_nested_attributes_for :stock

    has_one_attached :image
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :user
    belongs_to :product

    validates:user_id,{presence: true}
    validates:product_id,{presence: true}

    def buy
      stock = product.stock
      stock.stock -= 1

      ActiveRecord::Base.transaction do
        save
        stock.save
      end
    end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :purchases

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザーを登録しました"
      redirect_to("/")
    end
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "ユーザー「#{@user.name}」を削除しました"
    redirect_to("/")
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to("/") unless current_user.admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end        
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @q = Product.ransack(params[:q])
    @categories = Category.all
    @products = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def new
    @product = Product.new
    @product.build_price
    @product.build_stock
  end

  def create
    @product = Product.new(product_params)
    if @product&.save
      flash[:notice] = "商品情報を登録しました"
      redirect_to("/")
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(update_product_params)
    flash[:notice] = "商品情報を更新しました"
    redirect_to("/")
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "商品情報を削除しました"
    redirect_to("/")
  end

  private

  def product_params
    params.require(:product).permit(:product_code, :name, :maker_id, :category_id, :image, price_attributes: [:price], stock_attributes: [:stock])
  end

  def update_product_params
    params.require(:product).permit(:product_code, :name, :maker_id, :category_id, price_attributes: [:price, :_destroy, :id], stock_attributes: [:stock, :_destroy, :id])
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

    def create
        @purchase = current_user.purchases.build(product_id:  params[:product_id])
        @purchase.buy
        flash[:notice] = "商品を購入しました"
        redirect_to("/")
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:notice] = "ログインしました"
      redirect_to("/")
    else
      render("/login")
    end
  end

  def destroy
    reset_session
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end
  
  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザーを登録しました"
      redirect_to("/")
    else
      render(new_user_path)
    end
  end

  def purchases
    @purchases = Purchase.where(user_id: current_user.id)
  end

  def show
  end

  def edit
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1 class="mt-2">ユーザー一覧</h1>

<table class="table">
<thead>
  <tr>
      <th>#</th>
      <th>ユーザー名</th>
      <th></th>
  </tr>
</thead>
<tbody>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.id%></td>
            <td><%= user.name%></td>
            <td><%= link_to("詳細", "/admin/users/#{user.id}", class:"btn btn-secondary" )%>
            <%= link_to("削除","/admin/users/#{user.id}",{method: "DELETE", data: {confirm: "削除しますか？"}, class:"btn btn-danger"}) %></td>
        </tr>
    <% end %>
</tbody>
</table>

app/views/admin/users/new.html.erb
<h1>新規ユーザー登録</h1>

<%= form_with(model: [:admin,@user], local: true) do |f|%>
    <%= f.label :名前%>
    <%= f.text_field :name, class:"form-control"%>
    <%= f.label :メールアドレス%>
    <%= f.email_field :email, class:"form-control"%>
    <%= f.check_box :admin, class:"form-check-input"%>
    <%= f.label :管理者権限%><br>
    <%= f.label :パスワード%>
    <%= f.text_field :password, class:"form-control"%>
    <%= f.label :パスワード（確認）%>
    <%= f.text_field :password_confirmation, class:"form-control"%>
    <%= f.submit "登録", class: "mt-3 btn btn-primary btn-lg btn-block"%>
<% end %>

app/views/admin/users/show.html.erb
<h2><%= current_user.name%></h2>
<p><%= current_user.email%></p>
<p>お届け先住所</p>
<p><%= link_to("注文履歴", "#")%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>

  <body>
   <div class="navbar navbar-expand-md navbar-light bg-light">
      <div class="navbar-brand">在庫管理アプリケーション</div>
      
      <% if session[:user_id]%>
        <%= link_to("#{current_user.name}さん", user_path(current_user.id), class:"nav-link")%>
        <%= link_to("ログアウト", logout_path, method: :delete, class:"nav-link")%>
      <% else %>
        <%= link_to("新規登録", new_user_path, class:"nav-link")%>
        <%= link_to("ログイン", login_path, class:"nav-link")%>
      <% end %>
      <% if session[:user_id] && current_user.admin? %>
        <%= link_to("ユーザー一覧",admin_users_path, class:"nav-link")%>
      <% end %>
      <%= link_to("商品一覧","/", class:"nav-linnk")%>

    </div>
    <div class="container">
      <div class="notifications">
        <% flash.each do |key, value|%>
          <%= content_tag(:div, value, class: key)%>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1 class="mt-2">編集</h1>
<%= link_to("一覧に戻る", "/")%>
<%= form_with(model: @product, local: true) do |f| %>
  <%= f.label :カテゴリー%><br>
  <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true%><br>
  <%= f.label :メーカー%><br>
  <%= f.collection_select :maker_id, Maker.all, :id, :name %><br>
  <%= f.label :商品コード%>
  <%= f.text_field :product_code, class: "form-control" %>
  <%= f.label :商品名%>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :単価%>
  <%= f.fields_for :price do |p|%>
    <%= p.text_field :price, class:"form-control"%>
  <% end %>
  <%= f.label :在庫数%>
  <%= f.fields_for :stock do |s|%>
    <%= s.text_field :stock, class:"form-control"%>
  <% end %>
  <%= f.label :image%>
  <%= f.file_field :image, class:"form-control"%>
  <%= f.submit "変更を確定", class: "mt-2 btn btn-primary"%>
<% end %>

app/views/products/index.html.erb
<h1 class="mt-2">在庫一覧</h1>
<%= search_form_for(@q) do |f|%>
    <%= f.label "カテゴリーで絞込" , class: "col-sm-2 col-form-lagel"%>
    <div class="col-cm-10">
        <%= f.collection_select :category_id_eq, @categories, :id, :name, include_blank: true%>
    </div>
    <%= f.submit "検索", class: "btn btn-info mt-2 mb-2"%>
<% end %>

<% if session[:user_id] && current_user.admin? %>
    <%= link_to("新規商品登録", "/products/new", class: "mb-2 btn btn-primary") %>
<% end %>

<div class="mb-3">
    <%= paginate @products%>
    <%= page_entries_info @products, entry_name: '商品'%>
</div>

<table class="table">
    <thead>
    <tr>
        <% if session[:user_id] && current_user.admin? %>
            <th>#</th>
        <% end%>
        <th><%= Category.human_attribute_name(:name)%></th>
        <th><%= Maker.human_attribute_name(:name)%></th>
        <th><%= Product.human_attribute_name(:product_code)%></th>
        <th><%= Product.human_attribute_name(:name)%></th>
        <th><%= Price.human_attribute_name(:price)%></th>
        <% if session[:user_id] && current_user.admin? %>
        <th><%= Stock.human_attribute_name(:stock)%></th>
            <th></th>
        <% end %>
        <th></th>
        <% if session[:user_id]%>
            <th></th>
        <% end %>
    </tr>
    </thead>
    <tbody>
        <% @products.each do |product| %>
            <tr>
                <% if session[:user_id] && current_user.admin? %>
                    <td><%= product.id%></td>
                <% end %>
                <td><%= product.category.name%></td>
                <td><%= product.maker.name%></td>
                <td><%= product.product_code%></td>
                <td><%= product.name%></td>
                <td><%= product.price&.price.floor%></td>
                <% if session[:user_id] && current_user.admin? %>
                    <td><%= product.stock&.stock%></td>
                <% end %>
                <td><%= image_tag product.image, size: "100x100" if product.image.attached?%></td>
                <% if session[:user_id] && current_user.admin? %>
                    <td>
                        <%= link_to("編集", "/products/#{product.id}/edit", class:"btn btn-primary" )%>
                        <%= link_to("削除","/products/#{product.id}",{method: "DELETE", data: {confirm: "削除しますか？"}, class:"btn btn-danger"}) %>
                    </td>
                <% end %>
                <% if session[:user_id]%>
                <td><%= button_to "購入する", product_purchases_path(product.id), data: {confirm: "購入します。よろしいですか？"}, class:"btn btn-success"%></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/products/new.html.erb
<h1 class="mt-2">商品情報登録</h1>
<%= link_to("一覧に戻る", "/")%>
<%= form_with(model: @product, local: true) do |f| %>
  <%= f.label :category_id%><br>
  <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true%><br>
  <%= f.label :メーカー%><br>
  <%= f.collection_select :maker_id, Maker.all, :id, :name, include_blank: true%><br>
  <%= f.label :product_code%>
  <%= f.text_field :product_code, class: "form-control" %>
  <%= f.label :name%>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :単価%>
  <%= f.fields_for :price do |p|%>
    <%= p.text_field :price, class:"form-control"%>
  <% end %>
  <%= f.label :在庫数%>
  <%= f.fields_for :stock do |s|%>
    <%= s.text_field :stock, class:"form-control"%>
  <% end %>
  <%= f.label :image%>
  <%= f.file_field :image, class:"form-control"%>
  <%= f.submit "登録", class: "mt-2 btn btn-primary"%>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>新規ユーザー登録</h1>

<%= form_with(model: @user, local: true) do |f|%>
    <%= f.label :名前%>
    <%= f.text_field :name, class:"form-control"%>
    <%= f.label :メールアドレス%>
    <%= f.email_field :email, class:"form-control"%>
    <%= f.label :パスワード%>
    <%= f.text_field :password, class:"form-control"%>
    <%= f.label :パスワード（確認）%>
    <%= f.text_field :password_confirmation, class:"form-control"%>
    <%= f.submit "登録", class: "mt-3 btn btn-primary btn-lg btn-block"%>
<% end %>

app/views/users/purchases.html.erb
<table class="table mt-5">
    <thead>
        <tr>
            <th>#</th>
            <th>商品名</th>
            <th>価格</th>
            <th>購入日</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @purchases.each do |purchase|%>
        <tr>
            <% product = Product.find_by(id: purchase.product_id)%>
            <td><%= purchase.id%></td>
            <td>
                <%= product.name %>
            </td>
            <td><%= product.price.price.floor%></td>
            <td><%= purchase.created_at%></td>
            <td><%= button_to "再購入する", "/purchases/#{product.id}/create", data: {confirm: "購入します。よろしいですか？"}, class:"btn btn-success"%></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<h2><%= current_user.name%></h2>
<p><%= current_user.email%></p>
<p>お届け先住所</p>
<p><%= link_to("注文履歴", "/users/#{current_user.id}/purchases")%></p>

<%= link_to("編集", "#", class:"btn btn-secondary mt-3")%>